### ISSUE TITLE
Sharing a Wi-Fi Tooltip Tweak

### ISSUE THREAD

**Issue by sergeyklay** [sejjy/mechabar#2]
Hi,

I’ve been using and adapting your project, and I wanted to take a moment to thank you for making it open-source. It’s a fantastic setup, and it was a great foundation for customizing my own Waybar configuration.

As a small token of appreciation, I wanted to share a tweak I made for displaying a tooltip with Wi-Fi connection details. If you’re interested, I’d be happy to share more details. Maybe it’ll fit into your project too!

---

Screenshot
![2024-10-16_172254-c](https://github.com/user-attachments/assets/c38450d2-e92e-4fca-9a79-5aac48478985)

config.jsonc
```jsonc
  "custom/wifi": {
    "exec": "~/.config/waybar/modules/essid.sh",
    "return-type": "json",
    "format": "{}",
    "tooltip": true,
    "interval": 5,
    "on-click": "foot -w 700x700 -a foot.nmtui bash -c 'sleep 0.1; nmtui'",
    "min-length": 7,
    "max-length": 7
  }
```

essid.sh
```sh
#!/bin/bash

# Get the current Wi-Fi ESSID
essid=$(nmcli -t -f active,ssid dev wifi | awk -F: '/^yes/ {print $2}')

# If no ESSID is found, set a default value
if [ -z "$essid" ]; then
  echo "{\"text\": \"󰤨 WiFi\", \"tooltip\": \"No Connection\"}"
else
  # Some defaults
  ip_address="127.0.0.1"
  gateway="127.0.0.1"
  mac_address="N/A"
  bssid="N/A"
  chan="N/A"
  signal="N/A"
  rx_bitrate=""
  tx_bitrate=""

  active_device=$(nmcli -t -f DEVICE,STATE device status | \
    grep -w "connected" | \
    grep -v -E "^(dummy|lo:)" | \
    awk -F: '{print $1}')

  if [ -n "$active_device" ]; then
    output=$(nmcli -e no -g IP4.ADDRESS,IP4.GATEWAY,GENERAL.HWADDR device show $active_device)

    ip_address=$(echo "$output" | sed -n '1p')
    gateway=$(echo "$output" | sed -n '2p')
    mac_address=$(echo "$output" | sed -n '3p')

    line=$(nmcli -e no -t -f ACTIVE,BSSID,CHAN,FREQ device wifi | grep "^yes")

    bssid=$(echo "$line" | awk -F':' '{print $2":"$3":"$4":"$5":"$6":"$7}')
    chan=$(echo "$line" | awk -F':' '{print $8}')
    freq=$(echo "$line" | awk -F':' '{print $9}')
    chan="$chan ($freq)"

    iw_output=$(iw dev "$active_device" station dump)
    signal=$(echo "$iw_output" | grep "signal:" | awk '{print $2 " dBm"}')

    # Upload speed
    rx_bitrate=$(echo "$iw_output" | grep "rx bitrate:" | awk '{print $3 " " $4}')

    # Download speed
    tx_bitrate=$(echo "$iw_output" | grep "tx bitrate:" | awk '{print $3 " " $4}')
  fi

  tooltip="$essid\n"
  tooltip+="\nIP Address:  ${ip_address}"
  tooltip+="\nRouter:      ${gateway}"
  tooltip+="\nMAC Address: ${mac_address}"
  tooltip+="\nBSSID:       ${bssid}"
  tooltip+="\nChannel:     ${chan}"
  tooltip+="\nSignal:      ${signal}"

  if [ -n "$rx_bitrate" ]; then
    tooltip+="\nRx Rate:     ${rx_bitrate}"
  fi

  if [ -n "$tx_bitrate" ]; then
    tooltip+="\nTx Rate:     ${tx_bitrate}"
  fi

  echo "{\"text\": \"󰤨 WiFi\", \"tooltip\": \"$tooltip\"}"
fi

```

---

Thanks again for your work!

Best,
Serghei

P.S. I'll continue work on this module a bit. Actual version can be fount [at my repo](https://github.com/sergeyklay/dotfiles/blob/master/.config/waybar/modules/essid.sh).

**Comment by sejjy** [comment]
Hi Serghei,

Thank you so much for your kind words and for sharing your tweak. I really appreciate it! :)

I like how the tooltip displays much more detail, and that `nmtui` offers a lot more compared to Rofi's limited functionalities.

If you could submit a pull request with your changes, I would be happy to review and merge them into the project. Although I'm _currently_ quite satisfied with Rofi as my network manager, this way, others can choose whichever option suits their preferences.

Thanks again for your contribution. If you have any more ideas or improvements, I would love to hear more from you.

Best regards,
Jesse
